### ISSUE TITLE
Docs: Message ID vs ID vs UID

### ISSUE THREAD

**Issue by steinroe** [postalsys/emailengine#108] opened 2022-01-11 17:59 UTC
Hi,

I am a bit confused about the ids of a message. I understand that the message id is the [Message-ID]( https://en.wikipedia.org/wiki/Message-ID), but what are id and uid? Could you shorty clarify where these are generated and what they represent?

Thanks!

PS:  Love emailengine so far!

**Comment by andris9** [comment] 2022-01-11 21:49
It's a great question. I probably should write a documentation page about it.

* `messageId` is the value from the `Message-ID` header. This value identifies the message, but not the copy, as you can have multiple messages with the same Message-ID value in your account (for example, if you send an email to yourself, you would have the same message in the Sent mail folder and INBOX).
* `uid` is the IMAP `UID` value. These values are immutable identifiers and unique per folder. Each message in a folder has a unique, incrementing UID value (messages added later will have a greater UID value than messages added before). It's kind of like the auto_increment ID in MySQL. If you create a new folder, then the first message will probably get UID 1, the second one gets 2, etc. If you delete a message, the UID value does not get recycled. It's always an incrementing value. The problem is that depending on the server implementation and the number of messages, you might run out of available UID numbers. To overcome this situation, IMAP allows to "reset" all UID values in a folder. This means that a special value UIDVALIDITY is updated, and UID values are reassigned to the messages in the folder (a message that previously had UID 66762864 now has UID 5)
* `id` in EmailEngine's context is an encoded value that combines the folder path, UIDVALIDITY, and UID values of a message. This means that knowing that value EmailEngine always returns the same email. If the server resets UID values in a folder, this id value becomes invalid and returns nothing. If you only rely on UID values, you might still get a match, but it would be a completely different email as the server reassigned UID values.

If you look at how other IMAP modules usually handle messages, then they use UID values. It is really easy to mess things up when using UIDs so EmailEngine uses its own id scheme to avoid the typical problems.

**Comment by steinroe** [comment] 2022-01-12 07:25
Thanks for the quick and elaborate answer!

On a use-case level, does this mean that I should use the
- `messageId` for reply-tracking (as presented in [this](https://docs.emailengine.app/tracking-email-replies-with-imap-api/) blog post) and
- the `id` for de-duplication of incoming messages?

Thanks!

**Comment by andris9** [comment] 2022-01-12 07:43
You should probably track `messageId` values. `id` value points to a specific entry in the mail account, which might cause issues in some cases. For example, suppose a user moves a message from one folder to another. In that case, the message in the initial folder generates a "delete" event, and the same message in the new folder generates a new message event (as it's new in that folder), and it also gets a new `id` value assigned. If you track `messageId` values, you can easily see that it's not a new message but still the same message you already know about even though it has a different `id`.

**Closed** 2022-01-13 09:55 UTC
